/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
package main

import (
	"fmt"
)

func main() {
	a := 1
	aprev := 1
	even := uint64(0)

	for a < 4000000 {
		n := a + aprev
		aprev = a
		a = n

		if n % 2 == 0 {
			even += uint64(n)
		}
	}

	fmt.Println(even)
}
